//
//  MusclesExpressionModel.swift
//  FaceReality
//
//  Created by Bianca Nathally Bezerra de Lima on 06/09/23.
//

import Foundation

struct Muscle: Hashable {
    let expression: String
    let muscleName: String
    let muscleDescription: String
    let muscleIllustrationName: String
}

struct SmileMuscles  {
    let muscles: [Muscle] = [Muscle(expression: "Sorriso",
                                    muscleName: String(localized: "orbicularolho-string"),
                                    muscleDescription: String(localized: "orbicularolhodescricao-string"),
                                    muscleIllustrationName: "orbicularOlho"),
                             Muscle(expression: "Sorriso",
                                    muscleName: String(localized: "levantadorlabioasanariz-string"),
                                    muscleDescription: String(localized: "levantadorlabioasanarizdescricao-string"),
                                    muscleIllustrationName: "levantadorLabioAsaNariz"),
                             Muscle(expression: "Sorriso",
                                    muscleName: String(localized: "levantadorlabio-string"),
                                    muscleDescription: String(localized: "levantadorlabiodescricao-string"),
                                    muscleIllustrationName: "levantadorLabio"),
                             Muscle(expression: "Sorriso",
                                    muscleName: String(localized: "zigomaticomaior-string"),
                                    muscleDescription: String(localized: "zigomaticomaiordescricao-string"),
                                    muscleIllustrationName: "zigomaticoMaior"),
                             Muscle(expression: "Sorriso",
                                    muscleName: String(localized: "zigomaticomenor-string"),
                                    muscleDescription: String(localized: "zigomaticomenordescricao-string"),
                                    muscleIllustrationName: "zigomaticoMenor"),
                             Muscle(expression: "Sorriso",
                                    muscleName: String(localized: "risorio-string"),
                                    muscleDescription: String(localized: "risoriodescricao-string"),
                                    muscleIllustrationName: "risorio"),
                             Muscle(expression: "Sorriso",
                                    muscleName: String(localized: "levantadoranguloboca-string"),
                                    muscleDescription: String(localized: "levantadorangulobocadescricao-string"),
                                    muscleIllustrationName: "levantadorAnguloBoca"),
                             Muscle(expression: "Sorriso",
                                    muscleName: String(localized: "orbicularboca-string"),
                                    muscleDescription: String(localized: "orbicularbocadescricao-string"),
                                    muscleIllustrationName: "orbicularBoca"),
                             Muscle(expression: "Sorriso",
                                    muscleName: String(localized: "bucinador-string"),
                                    muscleDescription: String(localized: "bucinadordescricao-string"),
                                    muscleIllustrationName: "bucinador"),
                             Muscle(expression: "Sorriso",
                                    muscleName: String(localized: "depressoranguloboca-string"),
                                    muscleDescription: String(localized: "depressorangulobocadescricao-string"),
                                    muscleIllustrationName: "depressorAnguloBoca")]
}

struct AngerMuscles {
    let muscles: [Muscle] = [Muscle(expression: "Raiva",
                                    muscleName: String(localized: "frontal-string"),
                                    muscleDescription: String(localized: "frontaldescricao-string"),
                                    muscleIllustrationName: "frontal"),
                             Muscle(expression: "Raiva",
                                    muscleName: String(localized: "corrugadorsupercilio-string"),
                                    muscleDescription: String(localized: "corrugadorsuperciliodescricao-string"),
                                    muscleIllustrationName: "corrugadorSupercilio"),
                             Muscle(expression: "Raiva",
                                    muscleName: String(localized: "procero-string"),
                                    muscleDescription: String(localized: "procerodescricao-string"),
                                    muscleIllustrationName: "procero"),
                             Muscle(expression: "Raiva",
                                    muscleName: String(localized: "orbicularolho-string"),
                                    muscleDescription: String(localized: "orbicularolhodescricao-string"),
                                    muscleIllustrationName: "orbicularOlho"),
                             Muscle(expression: "Raiva",
                                    muscleName: String(localized: "zigomaticomaior-string"),
                                    muscleDescription: String(localized: "zigomaticomaiordescricao-string"),
                                    muscleIllustrationName: "zigomaticoMaior"),
                             Muscle(expression: "Raiva",
                                    muscleName: String(localized: "zigomaticomenor-string"),
                                    muscleDescription: String(localized: "zigomaticomenordescricao-string"),
                                    muscleIllustrationName: "zigomaticoMenor"),
                             Muscle(expression: "Raiva",
                                    muscleName: String(localized: "levantadorlabioasanariz-string"),
                                    muscleDescription: String(localized: "levantadorlabioasanarizdescricao-string"),
                                    muscleIllustrationName: "levantadorLabioAsaNariz"),
                             Muscle(expression: "Raiva",
                                    muscleName: String(localized: "levantadorlabio-string"),
                                    muscleDescription: String(localized: "levantadorlabiodescricao-string"),
                                    muscleIllustrationName: "levantadorLabio"),
                             Muscle(expression: "Raiva",
                                    muscleName: String(localized: "levantadoranguloboca-string"),
                                    muscleDescription: String(localized: "levantadorangulobocadescricao-string"),
                                    muscleIllustrationName: "levantadorAnguloBoca")]
}

struct SurpriseMuscles {
    let muscles: [Muscle] = [Muscle(expression: "Espanto",
                                    muscleName: String(localized: "frontal-string"),
                                    muscleDescription: String(localized: "frontaldescricao-string"),
                                    muscleIllustrationName: "frontal"),
                             Muscle(expression: "Espanto",
                                    muscleName: String(localized: "procero-string"),
                                    muscleDescription: String(localized: "procerodescricao-string"),
                                    muscleIllustrationName: "procero"),
                             Muscle(expression: "Espanto",
                                    muscleName: String(localized: "orbicularolho-string"),
                                    muscleDescription: String(localized: "orbicularolhodescricao-string"),
                                    muscleIllustrationName: "orbicularOlho"),
                             Muscle(expression: "Espanto",
                                    muscleName: String(localized: "levantadorlabio-string"),
                                    muscleDescription: String(localized: "levantadorlabiodescricao-string"),
                                    muscleIllustrationName: "levantadorLabio"),
                             Muscle(expression: "Espanto",
                                    muscleName: String(localized: "zigomaticomaior-string"),
                                    muscleDescription: String(localized: "zigomaticomaiordescricao-string"),
                                    muscleIllustrationName: "zigomaticoMaior"),
                             Muscle(expression: "Espanto",
                                    muscleName: String(localized: "zigomaticomenor-string"),
                                    muscleDescription: String(localized: "zigomaticomenordescricao-string"),
                                    muscleIllustrationName: "zigomaticoMenor"),
                             Muscle(expression: "Espanto",
                                    muscleName: String(localized: "risorio-string"),
                                    muscleDescription: String(localized: "risoriodescricao-string"),
                                    muscleIllustrationName: "risorio")]
}

struct DisgustMuscles {
    let muscles: [Muscle] = [Muscle(expression: "Nojo",
                                    muscleName: String(localized: "frontal-string"),
                                    muscleDescription: String(localized: "frontaldescricao-string"),
                                    muscleIllustrationName: "frontal"),
                             Muscle(expression: "Nojo",
                                    muscleName: String(localized: "procero-string"),
                                    muscleDescription: String(localized: "procerodescricao-string"),
                                    muscleIllustrationName: "procero"),
                             Muscle(expression: "Nojo",
                                    muscleName: String(localized: "orbicularolho-string"),
                                    muscleDescription: String(localized: "orbicularolhodescricao-string"),
                                    muscleIllustrationName: "orbicularOlho"),
                             Muscle(expression: "Nojo",
                                    muscleName: String(localized: "levantadorlabioasanariz-string"),
                                    muscleDescription: String(localized: "levantadorlabioasanarizdescricao-string"),
                                    muscleIllustrationName: "levantadorLabioAsaNariz"),
                             Muscle(expression: "Nojo",
                                    muscleName: String(localized: "levantadorlabio-string"),
                                    muscleDescription: String(localized: "levantadorlabiodescricao-string"),
                                    muscleIllustrationName: "levantadorLabio"),
                             Muscle(expression: "Nojo",
                                    muscleName: String(localized: "orbicularboca-string"),
                                    muscleDescription: String(localized: "orbicularbocadescricao-string"),
                                    muscleIllustrationName: "orbicularBoca"),
                             Muscle(expression: "Nojo",
                                    muscleName: String(localized: "depressoranguloboca-string"),
                                    muscleDescription: String(localized: "depressorangulobocadescricao-string"),
                                    muscleIllustrationName: "depressorAnguloBoca")]
}

struct SadnessMuscles {
    let muscles: [Muscle] = [Muscle(expression: "Tristeza",
                                    muscleName: String(localized: "procero-string"),
                                    muscleDescription: String(localized: "procerodescricao-string"),
                                    muscleIllustrationName: "procero"),
                             Muscle(expression: "Tristeza",
                                    muscleName: String(localized: "corrugadorsupercilio-string"),
                                    muscleDescription: String(localized: "corrugadorsuperciliodescricao-string"),
                                    muscleIllustrationName: "corrugadorSupercilio"),
                             Muscle(expression: "Tristeza",
                                    muscleName: String(localized: "orbicularolho-string"),
                                    muscleDescription: String(localized: "orbicularolhodescricao-string"),
                                    muscleIllustrationName: "orbicularOlho"),
                             Muscle(expression: "Tristeza",
                                    muscleName: String(localized: "levantadorlabioasanariz-string"),
                                    muscleDescription: String(localized: "levantadorlabioasanarizdescricao-string"),
                                    muscleIllustrationName: "levantadorLabioAsaNariz"),
                             Muscle(expression: "Tristeza",
                                    muscleName: String(localized: "zigomaticomaior-string"),
                                    muscleDescription: String(localized: "zigomaticomaiordescricao-string"),
                                    muscleIllustrationName: "zigomaticoMaior"),
                             Muscle(expression: "Tristeza",
                                    muscleName: String(localized: "zigomaticomenor-string"),
                                    muscleDescription: String(localized: "zigomaticomenordescricao-string"),
                                    muscleIllustrationName: "zigomaticoMenor"),
                             Muscle(expression: "Tristeza",
                                    muscleName: String(localized: "risorio-string"),
                                    muscleDescription: String(localized: "risoriodescricao-string"),
                                    muscleIllustrationName: "risorio"),
                             Muscle(expression: "Tristeza",
                                    muscleName: String(localized: "levantadoranguloboca-string"),
                                    muscleDescription: String(localized: "levantadorangulobocadescricao-string"),
                                    muscleIllustrationName: "levantadorAnguloBoca"),
                             Muscle(expression: "Tristeza",
                                    muscleName: String(localized: "depressorlabio-string"),
                                    muscleDescription: String(localized: <#T##Foundation.LocalizedStringResource#>),
                                    muscleIllustrationName: "depressorLabio")]
}
